### ISSUE TITLE
realm app does not initialize on miniflare

### ISSUE THREAD

**Issue by syffs** [mongodb-developer/cloudflare-worker-rest-api-realm-atlas#5]
I'm getting the below exception when using realm-web on miniflare:
```sh
 Error: DefaultNetworkTransport.AbortController must be set before it's used
    at new Er (/project/node_modules/realm-web/dist/bundle.dom.es.js:230:19)
    at new Ar (/project/node_modules/realm-web/dist/bundle.dom.es.js:3171:38)
    at qd (/project/src/index.ts:156:18)
    at Object.handler (/project/src/index.ts:241:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at run (/project/node_modules/worktop/router/index.mjs:69:34)
    at fetch (/project/node_modules/worktop/cache/index.mjs:22:40)
    at EventTarget.[dispatchFetch] (/project/node_modules/miniflare/src/modules/events.ts:207:25)
    at Miniflare._Miniflare_httpRequestListener (/project/node_modules/miniflare/src/index.ts:416:20)
```

in my project: `    at qd (/project/src/index.ts:156:18)` is:
```js
App = App || new Realm.App(appId)
```
Here is [repro](https://github.com/syffs/cloudflare-worker-rest-api-realm-atlas/tree/miniflare) with this repo as base.

**Comment by syffs** [comment]
Took me a while, but I figured out that miniflare v1 does not handle [latest workers runtime](https://community.cloudflare.com/t/2021-9-24-workers-runtime-release-notes/308821) with. 

Miniflare v2 (still in rc) has broader support for [web standards](https://v2.miniflare.dev/core/standards) including `AbortController`.

Upgrading miniflare fixes this.

**Comment by MaBeuLux88** [comment]
I'm glad to hear that you solved your problem!
Cheers,
Maxime.
